name: Deploy with Manual Approval

on:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Build Project
        run: vercel build --yes --token $VERCEL_TOKEN_1  # Generate .vercel/output
        env:
          VERCEL_TOKEN_1: ${{ secrets.VERCEL_TOKEN_1 }}

      - name: Deploy to Preview
        id: deploy
        run: |
          # Deploy using prebuilt output
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --yes --token $VERCEL_TOKEN_1)
          echo "Preview URL: $DEPLOYMENT_URL"
          
          # Extract deployment ID from URL
          DEPLOYMENT_ID=$(echo "$DEPLOYMENT_URL" | cut -d '.' -f1)
          
          # Save outputs
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN_1: ${{ secrets.VERCEL_TOKEN_1 }}

    outputs:
      deployment_id: ${{ steps.deploy.outputs.deployment_id }}

  approve-and-promote:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: "aseemfaras"  # Replace with actual username(s)

      - name: Promote to Production
        run: |
          curl -X POST \
            "https://api.vercel.com/v13/deployments/${{ needs.deploy-preview.outputs.deployment_id }}/promote" \
            -H "Authorization: Bearer $VERCEL_TOKEN_1" \
            -H "Content-Type: application/json" \
            -d '{"target": "production"}'
        env:
          VERCEL_TOKEN_1: ${{ secrets.VERCEL_TOKEN_1 }}  # Fixed token reference