name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment Approval Request
        run: |
          echo "Approval required for production deployment!"
          echo "PR merged: ${{ github.event.head_commit.message}}"

  deploy:
    needs: request-approval
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Wait for Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.PAT_TOKEN_TOKEN }}
          approvers: aseemfaras
          minimum-approvals: 1

      - name: Trigger Production Deployment
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}  


        