name: Deploy with Manual Approval

on:
  push:
    branches:
      - dev

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mock Install Dependencies
        run: |
          echo "Installing dependencies..."
          echo "Dependencies installed successfully!"

      - name: Mock Build Project
        run: |
          echo "Building project..."
          echo "Project built successfully!"

      - name: Mock Tests
        run: |
          echo "Running tests..."
          echo "All tests passed successfully!"

  production-approval:
    needs: build-and-verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create Release PR
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "main"
          github_token: ${{ secrets.PAT_TOKEN }}
          pr_title: "Production Release: ${{ github.event.head_commit.timestamp }}"
          pr_body: "Automated production release from dev branch"

      - name: Verify PR Status
        id: check-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ steps.create-pr.outputs.pr_number }}
              });
              
              core.setOutput('pr_state', pr.state);
              core.setOutput('merged', pr.merged);
              console.log('PR Status:', { state: pr.state, merged: pr.merged });
            } catch (error) {
              core.setFailed(`Failed to check PR status: ${error.message}`);
            }

      - name: Manual Approval
        if: steps.check-pr.outputs.pr_state == 'open' && steps.check-pr.outputs.merged != 'true'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.PAT_TOKEN }}
          approvers: aseemfaras
          minimum-approvals: 1

      - name: Merge to Production
        id: merge-prod
        if: success() && steps.check-pr.outputs.pr_state == 'open'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ steps.create-pr.outputs.pr_number }}
              });

              if (pr.merged) {
                console.log('PR already merged - skipping merge');
                core.setOutput('merge_performed', 'false');
                return;
              }

              const response = await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ steps.create-pr.outputs.pr_number }},
                merge_method: 'squash'
              });
              
              console.log('Merge successful:', response.data.message);
              core.setOutput('merge_performed', 'true');
            } catch (error) {
              core.setFailed(`Merge failed: ${error.message}`);
            }

      - name: Trigger Vercel Deployment
        if: steps.merge-prod.outputs.merge_performed == 'true'
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}