name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-artifacts
          path: build/

      - name: Create deployment approval link
        run: |
          echo "Manual deployment required!"
          echo "Approvers: Please visit https://github.com/$GITHUB_REPOSITORY/actions/workflows/${{ github.workflow }}.yml and trigger the 'deploy' job manually after reviewing changes."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: build-artifacts
          path: build/

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN_1}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: build/
          vercel-args: --prod