name: Deploy to Vercel (Production & Notifications)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, closed]
  issues:
    types: [opened]

jobs:
  prod-deployment:
    # This job runs only when:
    #   - A push is made to the main branch, OR
    #   - A pull request on main is closed and merged.
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment (Prod)
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" ]; then
            echo "Triggering production deployment via deploy hook..."
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
            echo "Deployment trigger sent successfully!"
          else
            echo "Error: VERCEL_DEPLOY_HOOK_URL secret not configured"
            exit 1
          fi

  notify-event:
    if: github.event_name == 'issues' || (github.event_name == 'pull_request' && github.event.action == 'opened')
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification for Event
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            LINK="${{ github.event.pull_request.html_url }}"
            MESSAGE="🚀 *New Pull Request Created!*\n\n🔗 [View Pull Request]($LINK)"
          elif [ "${{ github.event_name }}" = "issues" ]; then
            LINK="${{ github.event.issue.html_url }}"
            MESSAGE="🚀 *New Issue Created!*\n\n🔗 [View Issue]($LINK)"
          fi
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$MESSAGE\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
