name: Deploy with Manual Approval

on:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest  # Explicitly install the latest version

      - name: Deploy to Preview
        id: deploy
        run: |
          # Deploy to Vercel preview and get the URL
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --yes --token $VERCEL_TOKEN)
          echo "Preview URL: $DEPLOYMENT_URL"
          
          # Extract deployment ID from the URL (example: abcdef.vercel.app → abcdef)
          DEPLOYMENT_ID=$(echo "$DEPLOYMENT_URL" | cut -d '.' -f1)
          
          # Save outputs for the next job
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_1}}
    
    # Expose the deployment ID as a job output
    outputs:
      deployment_id: ${{ steps.deploy.outputs.deployment_id }}

  approve-and-promote:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: "your-github-username" # Replace with actual usernames

      - name: Promote to Production
        run: |
          # Use the Vercel API to promote the deployment
          curl -X POST \
            "https://api.vercel.com/v13/deployments/${{ needs.deploy-preview.outputs.deployment_id }}/promote" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"target": "production"}'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_1}}